### ISSUE TITLE
Protontricks doesn't "see" Civ V

### ISSUE THREAD

**Issue by MIS-g** [TeaDrinkingProgrammer/Civilization-V-Vox-Populi-on-Linux#2]
Thank you for you guide.  I pressed "open with Protontricks Launcher" but it didn't give me a Civ 5 option.  (or Sid Meiers...).  I checked several times.  It did give options for a lot of other games that I also have on my steamdeck (Age of Wonders Planetfall, Gloomhaven etc.).  Is there any way I can fix this?  I have played Civ V unmodded on the steamdeck, and the shortcut is on the steamdeck "desktop", so it's definitely on the machine.

Thank you for your help.

**Comment by TeaDrinkingProgrammer** [comment]
Can you checked if you have forced compatibily on for Civ5? Can you include a screenshot of that page as well?

**Comment by MIS-g** [comment]
How do I check this?  I tried googling, but it just talked about steam deck compatibility (verified, etc.)

**Comment by TeaDrinkingProgrammer** [comment]
Ah, I see. With forced compatibility, I mean the option for a game, not the compatibily rating for the Steam deck. You set this via the options of the game. On desktop, this is right mouseclick on the game in the library, then options and then compatibility.

**Comment by TeaDrinkingProgrammer** [comment]
The explanation is that by default, Linux systems use the Linux port if it exists (which it does for Civ5). With forced compatibility, you force Steam to download the Windows version

**Comment by MIS-g** [comment]
I can promise I didn't change it from the default!  I right-clicked the icon on the desktop, and "Kate" came up.  I don't see anything the says "Library", "Windows", or "Linux".

**Comment by TeaDrinkingProgrammer** [comment]
No, you do have to change the default. I mean the library in Steam itself

**Comment by MIS-g** [comment]
I see the note "runs on this computer via Steam Play.  Steam Linux Runtime selected by Valve testing."

**Comment by TeaDrinkingProgrammer** [comment]
I do not know what you mean exactly. Could you share a screenshot?

**Comment by MIS-g** [comment]
I sent you a screenshot via email.  I just found what you were looking for.  "Force the use of a specific Steam Play compatibility tool" is NOT checked.

**Comment by TeaDrinkingProgrammer** [comment]
That is the one you should check, then it "updates" (installs the Windows version" and the rest should work

**Comment by MIS-g** [comment]
Perfect, protonlinks found it.  Everything seems to be working now.  I greatly appreciate your time.  I could not have done it without your help.

**Comment by TeaDrinkingProgrammer** [comment]
Glad to help :)

**Comment by MIS-g** [comment]
Thank you so much for your help last week. Unfortunately, it seems to have
broken again. I haven't done anything with the files, or even opened up
desktop mode. On the civ v main menu, I can see the options (Play game,
setup game, mods et cetera) but when I mouse over them it doesn't highlight
and I cannot select any of them. Do you have any suggestion to fix this, or
should I just uninstall the game and start again? I really appreciate all
your time.

**Comment by TeaDrinkingProgrammer** [comment]
Maybe try alt-tabbing? Maybe take a look at this post: https://www.reddit.com/r/civ/comments/ieh0hh/whenever_i_launch_the_game_all_of_the_buttons_are/. I suggest googling for an answer because this does not have much to do with the guide anymore so I can't help you any more than Google at this point.
